# Generated by Django 5.1.6 on 2026-05-21 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True, verbose_name='Patient ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='scans/original/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_severity_index', models.IntegerField(default=0)),
                ('confidence_breakdown', models.JSONField(blank=True, null=True)),
                ('mask_blood_vessel', models.CharField(blank=True, max_length=255, null=True)),
                ('mask_hemorrhage', models.CharField(blank=True, max_length=255, null=True)),
                ('mask_hard_exudate', models.CharField(blank=True, max_length=255, null=True)),
                ('mask_microaneurysm', models.CharField(blank=True, max_length=255, null=True)),
                ('mask_optic_disc', models.CharField(blank=True, max_length=255, null=True)),
                ('mask_soft_exudate', models.CharField(blank=True, max_length=255, null=True)),
                ('combined_overlay', models.ImageField(blank=True, null=True, upload_to='scans/overlays/')),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('final_diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('final_severity_index', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Doctor Review'), ('REFERRED', 'Referred to Specialist'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='workflow.patient')),
            ],
        ),
    ]
