# Generated by Django 5.2.14 on 2026-05-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='explainability_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
